#!/bin/bash

DOCKER_GO_CONFIG_FILE=${HOME}/.config/docker-go

if [ -r ${DOCKER_GO_CONFIG_FILE} ]; then
  . ${DOCKER_GO_CONFIG_FILE}
fi

if [ -r .docker-go ]; then
  . .docker-go
fi

if [ -r .docker-go.local ]; then
  . .docker-go.local
fi

DOCKER_GO_CACHE_DIR=${DOCKER_GO_CACHE_DIR:-${HOME}/.cache/docker-go}
DOCKER_GO_TARGET_BIN_DIR=${DOCKER_GO_TARGET_BIN_DIR:-${HOME}/.bin}
DOCKER_GO_GO_VERSION=${DOCKER_GO_GO_VERSION:-1.5}
DOCKER_GO_DOCKER_IMAGE=${DOCKER_GO_DOCKER_IMAGE:-golang}
DOCKER_GO_NAMESPACE=${DOCKER_GO_NAMESPACE:-docker-go}

PROGRAM=$(basename $0)

do_link() {
    test -L ${DOCKER_GO_TARGET_BIN_DIR}/$1 || (echo "link: $1" && ln -s ${BASE_DIR}/docker-go ${DOCKER_GO_TARGET_BIN_DIR}/$1)
}

if [ "${PROGRAM}" = "docker-go" ]; then
    BASE_DIR=$(cd $(dirname $0) && pwd -P)

    if [ "$1" = "init" ]; then
        for BIN in docker-go go gofmt godoc
        do
            do_link ${BIN}
        done

        echo "Add '${DOCKER_GO_TARGET_BIN_DIR}' to your PATH"

    elif [ "$1" = "rehash" ]; then
        for BIN in $(find ${DOCKER_GO_CACHE_DIR}/bin -type f -maxdepth 1 -exec basename {} \; )
        do
            do_link ${BIN}
        done
    elif [ "$1" = "config" ]; then
        echo "DOCKER_GO_GO_VERSION: ${DOCKER_GO_GO_VERSION}"
        echo "DOCKER_GO_TARGET_BIN_DIR: ${DOCKER_GO_TARGET_BIN_DIR}"
        echo "DOCKER_GO_DOCKER_IMAGE: ${DOCKER_GO_DOCKER_IMAGE}"
        echo "DOCKER_GO_CACHE_DIR: ${DOCKER_GO_CACHE_DIR}"
        echo "DOCKER_GO_CONFIG_FILE: ${DOCKER_GO_CONFIG_FILE}"
        echo "DOCKER_GO_NAMESPACE: ${DOCKER_GO_NAMESPACE}"
    else
        echo "Usage:"
        echo " - init"
        echo " - rehash"
        echo " - config"
        echo
    fi
    exit 0
fi

# export GOOS=${GOOS:-darwin}

docker run \
    -e "GOOS" \
    -e "GOARCH" \
    -e "GO15VENDOREXPERIMENT" \
    -v ${DOCKER_GO_CACHE_DIR}:/go \
    -v $(pwd):/go/src/${DOCKER_GO_NAMESPACE} \
    -w /go/src/${DOCKER_GO_NAMESPACE} \
    --rm \
    ${DOCKER_GO_DOCKER_IMAGE}:${DOCKER_GO_GO_VERSION} \
    ${PROGRAM} $@

exit $?
